services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    environment:
      - WEBUI_SECRET_KEY=3f45f22f1529bb6be228fb4a788e5bbc8ab11b777f2c2f7a8b6483ff25ca1809
      - OLLAMA_BASE_URLS=http://ws-rarebox:11434;http://ws-vision:11434;http://ws-minifridge:11434
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
deploy:
  resources:
    reservations:
      devices:
        - driver: nvidia
          count: all
          capabilities: [gpu]