# Quinoa configuration
quarkus.quinoa.dev-server.port=3000
quarkus.quinoa.dev-server.check-timeout=8000

# H2 datasource configuration for local development
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:h2:./timetables.db
quarkus.hibernate-orm.database.generation=drop-and-create
