#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Prefer the actual home directory of the current shell, and fall back to the
# expected devcontainer user home when USER is not available.
USER_HOME="${HOME:-/home/${USER:-vscode}}"
USER_DOTS="${USER_HOME}/dots"
export USER_HOME

export MY_CREDENTIALS="$HOME/.my-credentials"  # Relative to $USER_HOME; can be overridden by MY_CREDENTIALS env var
cd "$WORKSPACE_ROOT"

if [ "$(id -u)" -eq 0 ]; then
    echo "⚠ Running as root; continuing with $USER_HOME" >&2
fi

read_credentials_tuple() {
    local file="$1"
    local line name email

    if [ ! -f "$file" ]; then
        return 1
    fi

    # Read exactly two non-empty, non-comment lines.
    name=""
    email=""
    while IFS= read -r line; do
        line="${line#"${line%%[![:space:]]*}"}"   # ltrim
        line="${line%"${line##*[![:space:]]}"}"   # rtrim
        [ -z "$line" ] && continue
        case "$line" in \#*) continue ;; esac

        if [ -z "$name" ]; then
            name="$line"
        elif [ -z "$email" ]; then
            email="$line"
            break
        fi
    done < "$file"

    if [ -z "$name" ] || [ -z "$email" ]; then
        return 1
    fi

    printf '%s\n%s\n' "$name" "$email"
}

apply_credentials() {
    local tuple
    tuple=$(read_credentials_tuple "${MY_CREDENTIALS}") || {
        echo "⚠ Credentials file missing or malformed at MY_CREDENTIALS=${MY_CREDENTIALS}; skipping credential config."
        return
    }

    local name email
    name=$(printf '%s\n' "$tuple" | sed -n '1p')
    email=$(printf '%s\n' "$tuple" | sed -n '2p')

    # Basic email shape check.
    if ! printf '%s\n' "$email" | grep -Eq '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'; then
        echo "⚠ Credentials file contains an invalid email address; skipping credential config."
        return
    fi

    # Git identity.
    git config --global user.name "$name"
    git config --global user.email "$email"

    # Shell environment for child processes and dotfiles.
    export GIT_NAME="$name"
    export GIT_EMAIL="$email"

    # Persist for interactive shells (idempotent append).
    if [ -d "$USER_HOME" ]; then
        local env_fragment="$USER_HOME/.my-credentials-env"
        {
            echo "# Auto-generated by devcontainer update-dots; do not edit manually."
            echo "export GIT_NAME='$name'"
            echo "export GIT_EMAIL='$email'"
        } > "$env_fragment"

        for rc in "$USER_HOME/.bashrc" "$USER_HOME/.zshrc"; do
            if [ -f "$rc" ]; then
                if ! grep -Fxq "source \"$env_fragment\"" "$rc" 2>/dev/null; then
                    echo "source \"$env_fragment\"" >> "$rc"
                fi
            fi
        done
    fi

    # GitHub CLI defaults for repositories created with gh.
    if command -v gh >/dev/null 2>&1; then
        gh config set git_protocol ssh >/dev/null 2>&1 || true
        gh config set prompt disabled >/dev/null 2>&1 || true
    fi

    echo "✅ Credentials configured: $name <$email>"
}

if [ -n "${MY_CREDENTIALS}" ]; then
    apply_credentials
else
    echo "⚠ MY_CREDENTIALS is unset; skipping credential config."
fi

if [ -d "${USER_DOTS}" ]; then
    echo "$USER_DOTS exists, $MY_CREDENTIALS is set"
    CREDS=$(echo "${USER_HOME}/.my-credentials-env")
    if [ -e "$CREDS" ]; then
        echo "$CREDS exists"
        echo "All checks pass"
        exit 0
    fi
fi

ensure_github_known_hosts() {
    # A freshly rebuilt container has no ~/.ssh/known_hosts, so the first
    # git@github.com operation would fail host-key verification in the
    # non-interactive post-create context. Populate known_hosts with
    # GitHub's published host keys (pinned; updated 2025).
    local ssh_dir="$USER_HOME/.ssh"
    local known_hosts="$ssh_dir/known_hosts"

    mkdir -p "$ssh_dir"
    chmod 700 "$ssh_dir"

    # GitHub's published SSH host keys (https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints)
    if ! grep -q "github.com" "$known_hosts" 2>/dev/null; then
        {
            echo "# github.com SSH host keys (pinned $(date +%Y-%m-%d))"
            echo "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl"
            echo "github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg="
            echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk="
        } >> "$known_hosts"
        chmod 644 "$known_hosts"
        echo "✅ Added GitHub host keys to $known_hosts"
    fi
}

ensure_github_known_hosts

echo "🛠 Running update-dots bootstrap in devcontainer for user: $USER_HOME"

# Each entry is: relative-path|space-separated-packages
PRE_INIT_NPM_INSTALL_PACKAGES=(
    "personal/pagerts|@types/node"
)

NVM_VERSION="v0.40.5"
NVM_DIR="${NVM_DIR:-$HOME/.nvm}"

# Source the install-extra.sh script that contains missing functions
if [ -f "$SCRIPT_DIR/install-extra.sh" ]; then
    source "$SCRIPT_DIR/install-extra.sh"
else
    echo "⚠ install-extra.sh not found"
fi

# Install any missing packages from REQUIRED_PACKAGES array (requires sudo for apt-get)
# Note: This runs as the container user, so sudo is needed if packages are actually missing.
# The Dockerfile should install all packages during build to avoid this requirement.
if type install_missing_apt_packages >/dev/null 2>&1; then
    install_missing_apt_packages || echo "⚠ Package installation skipped (may require root privileges)."
fi

install_local_cli_helpers() {
    echo "🧰 Installing local CLI helpers..."

    mkdir -p "$HOME/.local/bin"

    echo "✅ Local CLI helpers installed."
}

# Function to install declared local NPM packages
install_declared_local_npm_packages() {
    echo ""
    echo "📦 Installing declared local NPM packages..."

    for entry in "${PRE_INIT_NPM_INSTALL_PACKAGES[@]}"; do
        local package_path="${entry%%|*}"
        local packages="${entry#*|}"

        if [ -d "$package_path" ]; then
            echo "Installing packages in $package_path: $packages"
            (
                cd "$package_path"
                read -r -a npm_packages <<< "$packages"
                npm install "${npm_packages[@]}"
            )
        else
            echo "⚠ Package path does not exist: $package_path"
        fi
    done

    echo "✅ Local NPM packages installed."
}

install_opencode_cli() {
    # Only install if opencode.json or .opencode/ exists in the workspace root
    if [ -f "opencode.json" ] || [ -d ".opencode" ]; then
        echo "🔧 Installing opencode-ai CLI..."

        mkdir -p "$HOME/.local/bin" "$HOME/.local/lib"
        export npm_config_prefix="$HOME/.local"
        npm install --global opencode-ai

        # Ensure the executable is on PATH for this and future shells.
        if ! grep -Fq "$HOME/.local/bin" "$HOME/.bashrc" 2>/dev/null; then
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$HOME/.bashrc"
        fi
        if [ -f "$HOME/.zshrc" ] && ! grep -Fq "$HOME/.local/bin" "$HOME/.zshrc" 2>/dev/null; then
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$HOME/.zshrc"
        fi

        echo "✅ opencode-ai installed."
    else
        echo "⏭ Skipping opencode-ai installation (no opencode.json or .opencode/ found in workspace root)."
    fi
}

ensure_github_cli_auth() {
    if [ "${GH_AUTH_PROVIDER:-}" = "wsl-host" ]; then
        echo "✅ Skipping in-container gh auth bootstrap (GH_AUTH_PROVIDER=wsl-host)."
        echo "   Authenticate once on the WSL host; this container reads ~/.config/gh via bind mount."
        return
    fi

    if ! command -v gh >/dev/null 2>&1; then
        echo "⚠ GitHub CLI is not available; skipping gh auth bootstrap."
        return
    fi

    if gh auth status >/dev/null 2>&1; then
        echo "✅ GitHub CLI is already authenticated."
        return
    fi

    echo "🔐 GitHub CLI is not authenticated yet."
    echo "   Run 'gh auth login' after the dev container opens to finish first-time setup."
    echo "   If you want post-create to block for interactive login, rebuild with GH_AUTH_ON_CREATE=1."

    if [ "${GH_AUTH_ON_CREATE:-0}" = "1" ] && [ -t 0 ] && [ -t 1 ]; then
        gh auth login
    fi
}




# ─────────────────────────────────────────────────────────────────────────────

# Fallback in case `dotfiles` remoteEnv isn't available to the devcontainer postCreateCommand.
: "${dotfiles:=https://github.com/akinevz2/doftiles.git}"

echo "📂 Restoring dotfiles from $dotfiles ..."
restore_dotfiles() {
    if [ -d "$USER_HOME/dots" ]; then
        echo "✅ $USER_HOME/dots already exists; refreshing."
        cd "$USER_HOME/dots" && git pull
        return 0
    fi
}

git clone $dotfiles "$USER_HOME/dots" || restore_dotfiles
cd "$USER_HOME/dots" && make install || echo "⚠ Dotfiles restore failed; continuing with remaining setup."

# Handle potential submodule issues by attempting fallback strategies
(git submodule update --init --recursive --remote) || \
    echo "⚠ Submodule initialization failed"

echo "✅ Environment setup complete!"
echo ""

install_opencode_cli

echo "Verifying installations..."
bash -c "$(cat <<STRING
node -v; 
npm -v;
git --version;
gh --version;
java -version;
javac -version;
mvn -version;
STRING
)"

exit 0
